# Generated by Django 2.1.1 on 2018-10-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('location', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=10)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Confirmed'), (2, 'Not confirmed'), (3, 'Canceled')], default=1)),
                ('dapart', models.DateTimeField()),
                ('arrive', models.DateTimeField()),
                ('price', models.IntegerField(default=50000)),
            ],
        ),
    ]
