# Generated by Django 2.1.1 on 2018-10-17 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('ref', models.AutoField(primary_key=True, serialize=False)),
                ('payment', models.CharField(max_length=10, unique=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Booking', unique=True)),
            ],
        ),
    ]
